In [1]:
#Importing required libraries
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv('ctg_data1.csv')
df

b     e  AC  FM  UC  DL  DS  DP  DR   LB  ...  C  D  E  AD  DE  LD  \
0      240   357   0   0   0   0   0   0   0  120  ... -1 -1 -1  -1  -1  -1   
1        5   632   4   0   4   2   0   0   0  132  ... -1 -1 -1   1  -1  -1   
2      177   779   2   0   5   2   0   0   0  133  ... -1 -1 -1   1  -1  -1   
3      411  1192   2   0   6   2   0   0   0  134  ... -1 -1 -1   1  -1  -1   
4      533  1147   4   0   5   0   0   0   0  132  ... -1 -1 -1  -1  -1  -1   
...    ...   ...  ..  ..  ..  ..  ..  ..  ..  ...  ... .. .. ..  ..  ..  ..   
2121  2059  2867   0   0   6   0   0   0   0  140  ... -1 -1  1  -1  -1  -1   
2122  1576  2867   1   0   9   0   0   0   0  140  ... -1 -1  1  -1  -1  -1   
2123  1576  2596   1   0   7   0   0   0   0  140  ... -1 -1  1  -1  -1  -1   
2124  1576  3049   1   0   9   0   0   0   0  140  ... -1 -1  1  -1  -1  -1   
2125  2796  3415   1   1   5   0   0   0   0  142  ... -1 -1 -1  -1  -1  -1   

      FS  SUSP  CLASS  NSP  
0      1    -1      9    2  
1     -1    -1      6    1  
2     -1    -1      6    1  
3     -1    -1      6    1  
4     -1    -1      2    1  
...   ..   ...    ...  ...  
2121  -1    -1      5    2  
2122  -1    -1      5    2  
2123  -1    -1      5    2  
2124  -1    -1      5    2  
2125  -1    -1      1    1  

[2126 rows x 42 columns]

In [4]:
df.dtypes

b             int64
e             int64
AC            int64
FM            int64
UC            int64
DL            int64
DS            int64
DP            int64
DR            int64
LB            int64
AC.1        float64
FM.1        float64
UC.1        float64
DL.1        float64
DS.1        float64
DP.1        float64
ASTV          int64
MSTV        float64
ALTV          int64
MLTV        float64
Width         int64
Min           int64
Max           int64
Nmax          int64
Nzeros        int64
Mode          int64
Mean          int64
Median        int64
Variance      int64
Tendency      int64
A             int64
B             int64
C             int64
D             int64
E             int64
AD            int64
DE            int64
LD            int64
FS            int64
SUSP          int64
CLASS         int64
NSP           int64
dtype: object

In [5]:
df.isna().sum()

b           0
e           0
AC          0
FM          0
UC          0
DL          0
DS          0
DP          0
DR          0
LB          0
AC.1        0
FM.1        0
UC.1        0
DL.1        0
DS.1        0
DP.1        0
ASTV        0
MSTV        0
ALTV        0
MLTV        0
Width       0
Min         0
Max         0
Nmax        0
Nzeros      0
Mode        0
Mean        0
Median      0
Variance    0
Tendency    0
A           0
B           0
C           0
D           0
E           0
AD          0
DE          0
LD          0
FS          0
SUSP        0
CLASS       0
NSP         0
dtype: int64

In [6]:
df.dropna()

b     e  AC  FM  UC  DL  DS  DP  DR   LB  ...  C  D  E  AD  DE  LD  \
0      240   357   0   0   0   0   0   0   0  120  ... -1 -1 -1  -1  -1  -1   
1        5   632   4   0   4   2   0   0   0  132  ... -1 -1 -1   1  -1  -1   
2      177   779   2   0   5   2   0   0   0  133  ... -1 -1 -1   1  -1  -1   
3      411  1192   2   0   6   2   0   0   0  134  ... -1 -1 -1   1  -1  -1   
4      533  1147   4   0   5   0   0   0   0  132  ... -1 -1 -1  -1  -1  -1   
...    ...   ...  ..  ..  ..  ..  ..  ..  ..  ...  ... .. .. ..  ..  ..  ..   
2121  2059  2867   0   0   6   0   0   0   0  140  ... -1 -1  1  -1  -1  -1   
2122  1576  2867   1   0   9   0   0   0   0  140  ... -1 -1  1  -1  -1  -1   
2123  1576  2596   1   0   7   0   0   0   0  140  ... -1 -1  1  -1  -1  -1   
2124  1576  3049   1   0   9   0   0   0   0  140  ... -1 -1  1  -1  -1  -1   
2125  2796  3415   1   1   5   0   0   0   0  142  ... -1 -1 -1  -1  -1  -1   

      FS  SUSP  CLASS  NSP  
0      1    -1      9    2  
1     -1    -1      6    1  
2     -1    -1      6    1  
3     -1    -1      6    1  
4     -1    -1      2    1  
...   ..   ...    ...  ...  
2121  -1    -1      5    2  
2122  -1    -1      5    2  
2123  -1    -1      5    2  
2124  -1    -1      5    2  
2125  -1    -1      1    1  

[2126 rows x 42 columns]

In [7]:
df.isna().sum()

b           0
e           0
AC          0
FM          0
UC          0
DL          0
DS          0
DP          0
DR          0
LB          0
AC.1        0
FM.1        0
UC.1        0
DL.1        0
DS.1        0
DP.1        0
ASTV        0
MSTV        0
ALTV        0
MLTV        0
Width       0
Min         0
Max         0
Nmax        0
Nzeros      0
Mode        0
Mean        0
Median      0
Variance    0
Tendency    0
A           0
B           0
C           0
D           0
E           0
AD          0
DE          0
LD          0
FS          0
SUSP        0
CLASS       0
NSP         0
dtype: int64

In [8]:
Features=df.drop('NSP', axis=1)
Label=df['NSP']

In [9]:
Features.shape

(2126, 41)

In [10]:
Features_T=Features.T
#Features_T.columns= Features_T.iloc[0]
#Features_T.columns
     

In [11]:
height, width = Features.shape
unique_classes = np.unique(Label)
unique_classes

array([1, 2, 3], dtype=int64)

In [12]:
num_classes = len(unique_classes)

scatter_train = np.cov(Features_T)*(height - 1)
scatter_within = 0

In [13]:
for i in range(num_classes):
  class_items = np.flatnonzero(Label == unique_classes[i])
  scatter_within = scatter_within + np.cov(Features_T[class_items]) * (len(class_items)-1)

scatter_between = scatter_train - scatter_within

In [14]:
#Calculating Eigenvalues and Eigenvectors of the covariance matrix

eigen_values, eigen_vectors = np.linalg.eigh(np.linalg.pinv(scatter_within).dot(scatter_between))
        #print(eig_vectors.shape)
        #pc = Features.dot(eig_vectors[:,::-1][:,:self.n_components])

In [15]:
#sort the eigenvalues in descending order
sorted_index = np.argsort(eigen_values)[::-1]
 
sorted_eigenvalue = eigen_values[sorted_index]
#similarly sort the eigenvectors 
sorted_eigenvectors = eigen_vectors[:,sorted_index]
sorted_eigenvectors

array([[ 0.47328471,  0.24254816,  0.42273077, ...,  0.4187079 ,
        -0.24948019, -0.47328549],
       [ 0.52515062, -0.2159238 , -0.37658087, ..., -0.37297376,
         0.22209552, -0.52515193],
       [ 0.00600605, -0.0299112 , -0.05207816, ..., -0.05190328,
         0.03087553, -0.00590249],
       ...,
       [-0.00531066,  0.3409364 , -0.10848452, ...,  0.11113537,
         0.33409692, -0.00530811],
       [ 0.00305011, -0.31402115,  0.08722416, ..., -0.09110485,
        -0.31045626,  0.00304808],
       [-0.0026595 ,  0.08939132, -0.03727486, ...,  0.03698868,
         0.08649789, -0.00265837]])

In [16]:
# select the first n eigenvectors, n is desired dimension
# of our final reduced data.
 
n_components = 30 #you can select any number of components.
eigenvector_subset = sorted_eigenvectors[:,0:n_components]
eigenvector_subset

array([[ 4.73284706e-01,  2.42548158e-01,  4.22730767e-01, ...,
         8.29129884e-10,  1.75084263e-04,  1.34068591e-08],
       [ 5.25150622e-01, -2.15923804e-01, -3.76580874e-01, ...,
        -7.45679901e-10, -1.59898779e-04, -1.22500821e-08],
       [ 6.00604765e-03, -2.99112031e-02, -5.20781644e-02, ...,
        -1.06407866e-09, -7.82581272e-05, -5.41940335e-09],
       ...,
       [-5.31066280e-03,  3.40936403e-01, -1.08484516e-01, ...,
        -1.02330615e-04,  2.00944536e-08, -5.78326494e-04],
       [ 3.05011218e-03, -3.14021151e-01,  8.72241559e-02, ...,
        -1.03429624e-04,  1.94168951e-08, -5.40802645e-04],
       [-2.65949982e-03,  8.93913205e-02, -3.72748553e-02, ...,
         3.99870365e-05, -7.00939178e-09,  1.91278163e-04]])

In [17]:
#Transform the data 
Features_reduced = np.dot(eigenvector_subset.transpose(),Features.transpose()).transpose()
Features_reduced

array([[ 3.00219818e+02, -6.59348817e+01, -1.70108676e+01, ...,
         9.90617068e+01,  1.00025951e-01, -1.28116908e+02],
       [ 3.33399783e+02, -2.29947270e+02, -1.93619671e+02, ...,
         9.24791606e+01,  3.01640057e-02, -1.12933153e+02],
       [ 4.91985408e+02, -2.19317644e+02, -1.76595744e+02, ...,
         9.06049212e+01,  4.07623557e-02, -1.11771061e+02],
       ...,
       [ 2.10824773e+03, -2.76186628e+02, -2.68518904e+02, ...,
         8.83094570e+01, -1.93632970e-03, -1.14411608e+02],
       [ 2.34614498e+03, -3.72528378e+02, -4.39990770e+02, ...,
         8.93613947e+01, -7.44827520e-02, -1.13318812e+02],
       [ 3.11573744e+03, -1.55130774e+02, -6.22744079e+01, ...,
         7.76907103e+01,  7.51974901e-02, -1.07289059e+02]])

In [18]:
LDA_df = pd.DataFrame(Features_reduced)
LDA_df

0           1           2          3         4           5   \
0      300.219818  -65.934882  -17.010868  59.134109  5.841630   83.327259   
1      333.399783 -229.947270 -193.619671   4.845027  5.693786   63.120960   
2      491.985408 -219.317644 -176.595744   4.277874  5.725263   67.714516   
3      819.616537 -249.799605 -234.419300   3.927355  5.722207   63.298208   
4      853.750884 -211.772067 -165.231380   4.781802  1.616331   71.980936   
...           ...         ...         ...        ...       ...         ...   
2121  2479.152503 -223.564163 -163.022489  92.703419  0.322535   92.150031   
2122  2250.567885 -334.604935 -370.648195  70.359456  1.248045   60.715841   
2123  2108.247731 -276.186628 -268.518904  70.439100  1.281455   74.090075   
2124  2346.144981 -372.528378 -439.990770  71.624623  1.162021   51.774984   
2125  3115.737443 -155.130774  -62.274408  86.933066 -3.107642  114.572269   

            6         7          8          9   ...        20        21  \
0    -0.203210  1.659403  36.196855 -91.968354  ... -0.002267  0.110255   
1    -1.465665  2.311563   7.666650 -80.470326  ... -0.003334  0.018029   
2    -1.468014  2.353739   8.773341 -80.690226  ... -0.003360  0.022607   
3    -1.438139  2.366857   8.565352 -78.114242  ... -0.002995 -0.013419   
4    -0.417242  2.001489   8.154242 -77.966687  ... -0.003052  0.006072   
...        ...       ...        ...        ...  ...       ...       ...   
2121 -1.527702  0.190751  17.600564 -92.450005  ... -0.003137 -0.005352   
2122 -1.489576  0.354613   5.865257 -95.586637  ... -0.003182 -0.124425   
2123 -1.496242  0.369724   5.437626 -96.966088  ... -0.003152 -0.060575   
2124 -1.438131  0.284834   5.868631 -93.798655  ... -0.003194 -0.161814   
2125  0.505257 -0.223200  13.250592 -83.457917  ... -0.002923  0.050240   

              22         23        24        25          26         27  \
0    -122.249988  -1.983852  2.572899 -1.064909   22.913827  99.061707   
1    -188.295024 -10.673009  0.110363 -0.767863  116.502230  92.479161   
2    -186.815057 -10.984364  0.150685 -0.776914  113.477586  90.604921   
3    -152.420589 -13.923591  1.292883 -0.878854  148.155456  92.255626   
4    -154.356035 -12.008144  1.262265 -0.945057  114.884011  92.326319   
...          ...        ...       ...       ...         ...        ...   
2121 -175.330924 -14.094176  0.233724 -0.770489  158.297725  73.848051   
2122 -164.506915 -23.272635  1.227331 -0.835368  248.717643  87.812819   
2123 -166.149382 -18.131222  1.254267 -0.841777  197.032727  88.309457   
2124 -164.494766 -25.741789  1.240208 -0.836109  283.661615  89.361395   
2125 -157.698017 -10.252508  0.289897 -0.810527  123.420444  77.690710   

            28          29  
0     0.100026 -128.116908  
1     0.030164 -112.933153  
2     0.040762 -111.771061  
3     0.017624 -111.578693  
4     0.040376 -111.877076  
...        ...         ...  
2121  0.033719 -113.112121  
2122 -0.044587 -113.552095  
2123 -0.001936 -114.411608  
2124 -0.074483 -113.318812  
2125  0.075197 -107.289059  

[2126 rows x 30 columns]

In [19]:
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [20]:
# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(LDA_df, Label, test_size=0.3, random_state=1)
     

Decision Tree

In [21]:
from sklearn.tree import DecisionTreeClassifier
# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred_train = clf.predict(X_train)

In [22]:
print("Training-set accuracy (in %):",metrics.accuracy_score(y_train, y_pred_train)*100)

Training-set accuracy (in %): 99.93279569892472


In [23]:
# Create Decision Tree classifer object
clf = DecisionTreeClassifier(criterion="entropy", max_depth=8)

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy (in %):",metrics.accuracy_score(y_test, y_pred)*100)

Accuracy (in %): 95.92476489028213


Naive Bayes

In [24]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB() 
gnb.fit(X_train, y_train) 

y_pred_train = gnb.predict(X_train)

print('Training-set accuracy (in %):', metrics.accuracy_score(y_train, y_pred_train)*100)
     

Training-set accuracy (in %): 84.67741935483872


In [25]:
# making predictions on the testing set 
y_pred = gnb.predict(X_test)

print("Gaussian Naive Bayes model accuracy (in %):", metrics.accuracy_score(y_test, y_pred)*100)

Gaussian Naive Bayes model accuracy (in %): 82.13166144200626


Random Forest

In [26]:
# importing random forest classifier from assemble module
from sklearn.ensemble import RandomForestClassifier
     

In [27]:
# creating a RF classifier
rfcl = RandomForestClassifier(n_estimators = 100) 
 
# Training the model on the training dataset
rfcl.fit(X_train, y_train)

y_pred_train = rfcl.predict(X_train)

print('Training-set accuracy (in %):', metrics.accuracy_score(y_train, y_pred_train)*100)

Training-set accuracy (in %): 99.93279569892472


In [28]:
# performing predictions on the test dataset
y_pred = rfcl.predict(X_test)
 
print('Training-set accuracy (in %):', metrics.accuracy_score(y_test, y_pred)*100)

Training-set accuracy (in %): 96.55172413793103


SVM

In [29]:
#Import svm model
from sklearn import svm

#Create a svm Classifier
svmclf = svm.SVC(kernel='linear') # Linear Kernel

#Train the model using the training sets
svmclf.fit(X_train, y_train)

y_pred_train = svmclf.predict(X_train)

print('Training-set accuracy (in %):', metrics.accuracy_score(y_train, y_pred_train)*100)

Training-set accuracy (in %): 98.25268817204301


In [30]:
#Predict the response for test dataset
y_pred = svmclf.predict(X_test)

# using metrics module for accuracy calculation
print("SVM model accuracy (in %): ", metrics.accuracy_score(y_test, y_pred)*100)

SVM model accuracy (in %):  96.23824451410658
